name: Backend Continuous Integration

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Build
        run: cargo +nightly build --verbose

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Run tests
        run: cargo +nightly test --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Add clippy component
        run: rustup component add clippy --toolchain nightly
      - name: Clippy
        run: cargo +nightly clippy

  rustfmt:
    name: Lint (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Add rustfmt component
        run: rustup component add rustfmt --toolchain nightly
      - name: Lint (rustfmt)
        run: cargo +nightly fmt --check
